In [1]:
#1
import numpy as np

array= np.empty ([0,0])
print (array)


[]


In [2]:
#2
import numpy as np
arr1= [[1,1],
       [1,1],*
       [1,1]]
print(arr1)


[[1, 1], [1, 1], 1, 1]


In [3]:
#3
import numpy as np
arry1=np.full([3,9],9)
print(arry1)

[[9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]]


In [4]:
#4
import numpy as np
array2= np.array([[2,2],[5,7]])
zero_array= np.zeros_like(array2)
print(zero_array)

[[0 0]
 [0 0]]


In [5]:
#5
import numpy as np

arr = np.array([1, 2, 3, 4])
ones_arr = np.ones_like(arr)

print(ones_arr)


[1 1 1 1]


In [22]:
#6
import numpy as np

new_list = [1, 2, 3, 4]
np_array = np.array(new_list)

print(np_array)


[1 2 3 4]


In [3]:

#1
import numpy as np

arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [20]:
#2
import numpy as np
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
#3
identity = np.eye(3)
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#4
import numpy as np

rand_arr = np.random.random(30)
print("Mean =", rand_arr.mean())


Mean = 0.49753201660208707


In [17]:
#5
import numpy as np
rand_matrix = np.random.random((10, 10))
print("Min =", rand_matrix.min())
print("Max =", rand_matrix.max())


Min = 0.04281893398083625
Max = 0.9999802857983027


In [16]:
#6
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
#7
arr = np.array([1, 2, 0, 0, 4, 0])
r = arr[::-1]
print(r)


[0 4 0 0 2 1]


In [14]:
#8
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print(border)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
#9
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
#Task3
#1
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5,6,7,8]);
result = x+y
print(result)

[ 6  8 10 12]


In [11]:
#2
import numpy as np
v= np.array([9,10])
w= np.array([11, 12])
result = np.subtract(v, w)
print(result)

[-2 -2]


In [10]:
#3
import numpy as np
v= np.array([9,10])
w= np.array([11, 12])
result = np.multiply(v,w)
print(result)

[ 99 120]


In [9]:
#4
import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#now Adding square in each element
x_square = x**2
y_square = y**2
v_square = v**2
w_square = w**2

print(x_square)
print(y_square)
print(v_square)
print(w_square)

[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]


In [4]:
#5
import numpy as np

# Define your vectors first
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])
x = np.array([7, 8, 9])
y = np.array([1, 0, 1])

dot_vw = np.dot(v, w)
print(f"Dot product of v and w: {dot_vw}")

dot_xv = np.dot(x, v)
print(f"Dot product of x and v: {dot_xv}")

dot_xy = np.dot(x, y)
print(f"Dot product of x and y (matrix multiplication):\n{dot_xy}")


Dot product of v and w: 32
Dot product of x and v: 50
Dot product of x and y (matrix multiplication):
16


In [6]:
#6
import numpy as np

# Define the vectors first (you MUST do this)
x = np.array([7, 8, 9])
y = np.array([1, 0, 1])
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

# Concatenate x and y along rows
concatenated_xy_rows = np.concatenate((x, y), axis=0)
print("Concatenated x and y along rows:\n", concatenated_xy_rows)

# Concatenate v and w along columns
v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)

concatenated_vw_cols = np.concatenate((v_col, w_col), axis=1)
print("Concatenated v and w along columns:\n", concatenated_vw_cols)


Concatenated x and y along rows:
 [7 8 9 1 0 1]
Concatenated v and w along columns:
 [[1 4]
 [2 5]
 [3 6]]


In [7]:
import numpy as np

try:

    v_reshaped_as_row = v.reshape(1, -1)
    concatenated_xv = np.concatenate((x, v_reshaped_as_row), axis=0)
    print("Concatenated x and v along rows (after reshaping v):\n", concatenated_xv)
except ValueError as e:
    print(f"Error when trying to concatenate x and v: {e}")
    print("\nExplanation: The direct concatenation of a 2D array (x) and a 1D array (v) fails because numpy.concatenate requires that all input arrays must have the same number of dimensions (ndim), or compatible shapes if an axis is specified. In this case, x has 2 dimensions and v has 1 dimension. To concatenate them, one of the arrays needs to be reshaped to match the dimensions of the other. Above, I've reshaped 'v' to be a 2D array (1 row, 2 columns) so it can be concatenated as a new row to 'x'.")


Error when trying to concatenate x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

Explanation: The direct concatenation of a 2D array (x) and a 1D array (v) fails because numpy.concatenate requires that all input arrays must have the same number of dimensions (ndim), or compatible shapes if an axis is specified. In this case, x has 2 dimensions and v has 1 dimension. To concatenate them, one of the arrays needs to be reshaped to match the dimensions of the other. Above, I've reshaped 'v' to be a 2D array (1 row, 2 columns) so it can be concatenated as a new row to 'x'.
